export default [
  {
    id: 1,
    postedOn: new Date(),
    title: "Frontend Developer",
    type: "Full time",
    location: "Remote",
    companyName: "Teknorix",
    companyUrl: "https://teknorix.jobsoid.com/",
    skills: ["Javascript", "React.js", "Node.js"],
    link: "https://google.com/careers",
  },
  {
    id: 2,
    postedOn: new Date(),
    title: "DBA",
    type: "Part time",
    location: "Office",
    companyName: "Teknorix",
    companyUrl: "https://teknorix.jobsoid.com/",
    skills: ["Angular", "Node.js"],
    link: "https://yahoo.com/jobs",
  },
  {
    id: 3,
    postedOn: new Date(),
    title: "Backend Developer",
    type: "Part time",
    location: "Office",
    companyName: "Teknorix",
    companyUrl: "https://teknorix.jobsoid.com/",
    skills: ["Angular", "Node.js"],
    link: "https://yahoo.com/jobs",
  },
  {
    id: 4,
    postedOn: new Date(),
    title: "Angular Developer",
    type: "Part time",
    location: "Office",
    companyName: "Teknorix",
    companyUrl: "https://teknorix.jobsoid.com/",
    skills: ["Angular", "Node.js"],
    link: "https://yahoo.com/jobs",
  },
  {
    id: 5,
    postedOn: new Date(),
    title: "QA",
    type: "Part time",
    location: "Remote",
    companyName: "Teknorix",
    companyUrl: "https://teknorix.jobsoid.com/",
    skills: ["Angular", "Node.js"],
    link: "https://yahoo.com/jobs",
  },
  {
    id: 6,
    postedOn: new Date(),
    title: "Sales",
    type: "Full time",
    location: "Office",
    companyName: "Teknorix",
    companyUrl: "https://teknorix.jobsoid.com/",
    skills: ["Angular", "Node.js"],
    link: "https://yahoo.com/jobs",
  },
  {
    id: 7,
    postedOn: new Date(),
    title: "Lawyer",
    type: "Full time",
    location: "Office",
    companyName: "Teknorix",
    companyUrl: "https://teknorix.jobsoid.com/",
    skills: ["Angular", "Node.js"],
    link: "https://yahoo.com/jobs",
  },
];
